//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransLogisticEntities : DbContext
    {
        public TransLogisticEntities()
            : base("name=TransLogisticEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresy> Adresy { get; set; }
        public virtual DbSet<DaneWysylki> DaneWysylki { get; set; }
        public virtual DbSet<Magazyn> Magazyn { get; set; }
        public virtual DbSet<Paczka> Paczka { get; set; }
        public virtual DbSet<Pojazd> Pojazd { get; set; }
        public virtual DbSet<PozycjaZamowienia> PozycjaZamowienia { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<Przewoz> Przewoz { get; set; }
        public virtual DbSet<PrzyjecieZewnetrzne> PrzyjecieZewnetrzne { get; set; }
        public virtual DbSet<PrzyjecieZewnetrznePozycje> PrzyjecieZewnetrznePozycje { get; set; }
        public virtual DbSet<RodzajPaczki> RodzajPaczki { get; set; }
        public virtual DbSet<RodzajPrzejazdu> RodzajPrzejazdu { get; set; }
        public virtual DbSet<RozmiarPaczki> RozmiarPaczki { get; set; }
        public virtual DbSet<Stanowisko> Stanowisko { get; set; }
        public virtual DbSet<StatusPrzejazdu> StatusPrzejazdu { get; set; }
        public virtual DbSet<StatusZamowienia> StatusZamowienia { get; set; }
        public virtual DbSet<WydanieZewnetrzne> WydanieZewnetrzne { get; set; }
        public virtual DbSet<WydanieZewnetrznePozycje> WydanieZewnetrznePozycje { get; set; }
        public virtual DbSet<Zamowienie> Zamowienie { get; set; }
    }
}
