//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paczka
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paczka()
        {
            this.PozycjaZamowienia = new HashSet<PozycjaZamowienia>();
            this.WydanieZewnetrznePozycje = new HashSet<WydanieZewnetrznePozycje>();
            this.PrzyjecieZewnetrznePozycje = new HashSet<PrzyjecieZewnetrznePozycje>();
        }
    
        public int paczka_id { get; set; }
        public byte rozmiar_paczki_id { get; set; }
        public int rodzaj_paczki_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaZamowienia> PozycjaZamowienia { get; set; }
        public virtual RodzajPaczki RodzajPaczki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WydanieZewnetrznePozycje> WydanieZewnetrznePozycje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrzyjecieZewnetrznePozycje> PrzyjecieZewnetrznePozycje { get; set; }
        public virtual RozmiarPaczki RozmiarPaczki { get; set; }
    }
}
