//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pracownik()
        {
            this.Przewoz = new HashSet<Przewoz>();
        }
    
        public int pracownik_id { get; set; }
        public int adresy_id { get; set; }
        public int stanowisko_id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public int telefon { get; set; }
        public System.DateTime data_zatrudnienia { get; set; }
        public bool aktywnosc { get; set; }
        public string kto_dodal { get; set; }
        public System.DateTime kiedy_dodal { get; set; }
        public string kto_edytowal { get; set; }
        public Nullable<System.DateTime> kiedy_edytowal { get; set; }
        public string kto_usunal { get; set; }
        public Nullable<System.DateTime> kiedy_usunal { get; set; }
    
        public virtual Adresy Adresy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przewoz> Przewoz { get; set; }
        public virtual Stanowisko Stanowisko { get; set; }
    }
}
