//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienie()
        {
            this.PozycjaZamowienia = new HashSet<PozycjaZamowienia>();
            this.Przewoz = new HashSet<Przewoz>();
        }
    
        public int zamowienie_id { get; set; }
        public System.DateTime data_zamowienia { get; set; }
        public int dane_wysylki_id { get; set; }
        public byte status_zamowienia_id { get; set; }
        public int nr_zamowienia { get; set; }
        public int kod { get; set; }
        public decimal cena { get; set; }
        public string waluta { get; set; }
        public System.DateTime data_realizacji { get; set; }
        public bool aktywnosc { get; set; }
        public string kto_dodal { get; set; }
        public System.DateTime kiedy_dodal { get; set; }
        public string kto_edytowal { get; set; }
        public Nullable<System.DateTime> kiedy_edytowal { get; set; }
        public string kto_usunal { get; set; }
        public Nullable<System.DateTime> kiedy_usunal { get; set; }
    
        public virtual DaneWysylki DaneWysylki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PozycjaZamowienia> PozycjaZamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przewoz> Przewoz { get; set; }
        public virtual StatusZamowienia StatusZamowienia { get; set; }
    }
}
